dist: trusty
sudo: required
language: cpp
compiler: clang

before_script:
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
 provider: script
 script_cleanup: true
 script:
 - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulex-96:$BINTRAY_API_KEY "https://api.bintray.com/content/lex-96/hw/hw2/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER_Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

